PARAM_CERT_PATH = 'CERT_PEM'
PARAM_KEY_PATH = 'KEY_PEM'
PARAM_CA_PATH = 'CA_PATH'

ENV_DIR_STAGING = 'DIR_STAGING'
ENV_WEB_PORT = 'WEB_PORT'

DIR_DOWNLOAD = 'download'
DIR_DECHIFFRE = 'dechiffre'

DOMAINE_GROSFICHIERS = 'GrosFichiers'

EVENEMENT_GROSFICHIERS_CHANGEMENT_CONSIGNATION_PRIMAIRE = 'changementConsignationPrimaire'
