PARAM_CERT_PATH = 'CERT_PEM'
PARAM_KEY_PATH = 'KEY_PEM'
PARAM_CA_PATH = 'CA_PATH'

PARAM_REDIS_HOSTNAME = 'REDIS_HOSTNAME'
PARAM_REDIS_PORT = 'REDIS_PORT'
PARAM_REDIS_USERNAME = 'REDIS_USERNAME'
PARAM_REDIS_PASSWORD_PATH = 'REDIS_PASSWORD_PATH'
PARAM_REDIS_SESSION_DATABASE = 'REDIS_SESSION_DATABASE'

ENV_DIR_STAGING = 'DIR_STAGING'
ENV_WEB_PORT = 'WEB_PORT'

DIR_DOWNLOAD = 'download'
DIR_DECHIFFRE = 'dechiffre'

DOMAINE_GROSFICHIERS = 'GrosFichiers'

EVENEMENT_GROSFICHIERS_CHANGEMENT_CONSIGNATION_PRIMAIRE = 'changementConsignationPrimaire'

REDIS_USERNAME_DEFAULT = 'client_nodejs'
REDIS_SESSION_DATABASE = 2

HEADER_USER_ID = 'X-User-Id'
HEADER_USER_NAME = 'X-User-Name'

SESSION_USER_NAME = 'user_name'
SESSION_USER_ID = 'user_id'
SESSION_CHALLENGE_CERTIFICAT = 'challenge_certificat'
